const menu = [
    {
        id: 1,
        title: 'cherry flower',
        category: 'tree flower',
        price: 11.99,
        img: '../images/cherryTreeFlower.JPG',
        desc: ` When an unknown printer took a galley of type and scrambled it to make a type specimen book. `,
    },
    {
        id: 2,
        title: 'green flower',
        category: 'grass flower',
        price: 12.99,
        img: '../images/greenGrassFlower.JPG',
        desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. `,
    },
    {
        id: 3,
        title: 'yellow flower',
        category: 'grass flower',
        price: 13.99,
        img: '../images/mauveGrassFlower.JPG',
        desc: `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
    },
    {
        id: 4,
        title: 'pink tree flower',
        category: 'tree flower',
        price: 14.99,
        img: '../images/pinkTreeFlower.jpg',
        desc: `It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages. `,
    },
    {
        id: 5,
        title: 'tree branches one',
        category: 'sky flower',
        price: 15.99,
        img: '../images/treeSkyOne.JPG',
        desc: `And more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    },
    {
        id: 6,
        title: 'tree branches two',
        category: 'sky flower',
        price: 16.99,
        img: '../images/treeSkyTwo.JPG',
        desc: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,`,
    },
    {
        id: 7,
        title: 'tree branches three',
        category: 'sky flower',
        price: 17.99,
        img: '../images/treeSkyThree.JPG',
        desc: `Contrary to popular belief, Lorem Ipsum is not simply random text `,
    },
    {
        id: 8,
        title: 'willow tree flower',
        category: 'tree flower',
        price: 18.99,
        img: '../images/willowTreeFlower.JPG',
        desc: `Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text,`,
    },
    {
        id: 9,
        title: 'yellow grass flower',
        category: 'grass flower',
        price: 19.99,
        img: '../images/yellowGrassFlower.JPG',
        desc: `There are many variations of passages of Lorem Ipsum available`,
    },
];
export default menu;
